import * as Knex from "knex";

export async function seed(knex: Knex): Promise<void> {
  await knex("TAGS").del();
  await knex("TAGS").insert([
    { name: "Spot (Superdog)", id: 1 },
    { name: "Stripe", id: 2 },
    { name: "The Cyborg", id: 3 },
    { name: "Orphans", id: 4 },
    { name: "Executive", id: 5 },
    { name: "Grape", id: 6 },
    { name: "Peanut", id: 7 },
    { name: "Bat-bat", id: 8 },
    { name: "Mr. Sorcerer", id: 9 },
    { name: "The Krunlk", id: 10 },
    { name: "The Underwater Mutt", id: 11 },
    { name: "The Critic", id: 12 },
    { name: "Innocent Bystanders", id: 13 },
    { name: "The Brans of the Universe", id: 14 },
    { name: "Nefarious Villains", id: 15 },
    { name: "Jim-Jim", id: 16 },
    { name: "John A. Executive", id: 17 },
    { name: "Santa", id: 18 },
    { name: "The Flick", id: 19 },
    { name: "Regular Hawk", id: 20 },
    { name: "Gang Members", id: 21 },
    { name: "The Warmongrel", id: 22 },
    { name: "Ted", id: 23 },
    { name: "Joey", id: 24 },
    { name: "Houndstooth", id: 25 },
  ]);

  await knex("COMIC_TAGS").insert([
    { comic: 1, tag: 1 },
    { comic: 1, tag: 2 },
    { comic: 2, tag: 1 },
    { comic: 2, tag: 2 },
    { comic: 2, tag: 3 },
    { comic: 2, tag: 4 },
    { comic: 3, tag: 1 },
    { comic: 3, tag: 2 },
    { comic: 3, tag: 4 },
    { comic: 3, tag: 5 },
    { comic: 4, tag: 1 },
    { comic: 4, tag: 2 },
    { comic: 4, tag: 6 },
    { comic: 4, tag: 7 },
    { comic: 5, tag: 1 },
    { comic: 5, tag: 2 },
    { comic: 5, tag: 3 },
    { comic: 5, tag: 4 },
    { comic: 5, tag: 6 },
    { comic: 5, tag: 7 },
    { comic: 6, tag: 1 },
    { comic: 6, tag: 8 },
    { comic: 6, tag: 9 },
    { comic: 6, tag: 10 },
    { comic: 6, tag: 11 },
    { comic: 7, tag: 1 },
    { comic: 7, tag: 8 },
    { comic: 7, tag: 9 },
    { comic: 7, tag: 10 },
    { comic: 7, tag: 11 },
    { comic: 7, tag: 12 },
    { comic: 8, tag: 1 },
    { comic: 8, tag: 8 },
    { comic: 8, tag: 9 },
    { comic: 8, tag: 10 },
    { comic: 8, tag: 11 },
    { comic: 8, tag: 12 },
    { comic: 8, tag: 13 },
    { comic: 9, tag: 1 },
    { comic: 9, tag: 3 },
    { comic: 9, tag: 6 },
    { comic: 9, tag: 7 },
    { comic: 10, tag: 1 },
    { comic: 10, tag: 2 },
    { comic: 10, tag: 3 },
    { comic: 10, tag: 6 },
    { comic: 10, tag: 7 },
    { comic: 11, tag: 1 },
    { comic: 11, tag: 2 },
    { comic: 11, tag: 3 },
    { comic: 11, tag: 6 },
    { comic: 11, tag: 7 },
    { comic: 12, tag: 1 },
    { comic: 12, tag: 8 },
    { comic: 12, tag: 11 },
    { comic: 12, tag: 13 },
    { comic: 13, tag: 1 },
    { comic: 13, tag: 6 },
    { comic: 13, tag: 7 },
    { comic: 13, tag: 14 },
    { comic: 14, tag: 1 },
    { comic: 14, tag: 2 },
    { comic: 14, tag: 6 },
    { comic: 14, tag: 7 },
    { comic: 14, tag: 15 },
    { comic: 14, tag: 16 },
    { comic: 15, tag: 1 },
    { comic: 15, tag: 6 },
    { comic: 15, tag: 7 },
    { comic: 15, tag: 17 },
    { comic: 16, tag: 1 },
    { comic: 16, tag: 6 },
    { comic: 16, tag: 7 },
    { comic: 16, tag: 18 },
    { comic: 17, tag: 1 },
    { comic: 17, tag: 2 },
    { comic: 17, tag: 3 },
    { comic: 18, tag: 1 },
    { comic: 18, tag: 13 },
    { comic: 18, tag: 19 },
    { comic: 19, tag: 1 },
    { comic: 19, tag: 2 },
    { comic: 19, tag: 20 },
    { comic: 20, tag: 1 },
    { comic: 20, tag: 13 },
    { comic: 20, tag: 21 },
    { comic: 21, tag: 22 },
    { comic: 21, tag: 23 },
    { comic: 22, tag: 1 },
    { comic: 22, tag: 8 },
    { comic: 22, tag: 13 },
    { comic: 22, tag: 20 },
    { comic: 23, tag: 1 },
    { comic: 23, tag: 7 },
    { comic: 23, tag: 20 },
    { comic: 23, tag: 24 },
    { comic: 24, tag: 1 },
    { comic: 24, tag: 2 },
    { comic: 24, tag: 13 },
    { comic: 24, tag: 25 },
    { comic: 25, tag: 2 },
    { comic: 25, tag: 16 },
    { comic: 25, tag: 25 },
    { comic: 26, tag: 2 },
    { comic: 26, tag: 16 },
    { comic: 26, tag: 25 },
    { comic: 27, tag: 2 },
    { comic: 27, tag: 16 },
    { comic: 27, tag: 25 },
    { comic: 28, tag: 2 },
    { comic: 28, tag: 16 },
    { comic: 28, tag: 25 },
    { comic: 29, tag: 2 },
    { comic: 29, tag: 13 },
    { comic: 29, tag: 16 },
    { comic: 30, tag: 1 },
    { comic: 30, tag: 2 },
    { comic: 30, tag: 16 },
    { comic: 31, tag: 1 },
    { comic: 31, tag: 3 },
    { comic: 31, tag: 6 },
    { comic: 31, tag: 7 },
    { comic: 31, tag: 16 },
  ]);
}
